"""Built-in roleplay scenarios and guided lessons (Pingo-style catalog)."""


def S(id, emoji, cat, title, title_ja, desc, ai_role, user_role, setting, vocab, levels="N5-N1"):
    return {
        "id": id, "emoji": emoji, "category": cat, "title": title, "title_ja": title_ja,
        "description": desc, "ai_role": ai_role, "user_role": user_role,
        "setting": setting, "target_vocab": vocab, "levels": levels, "kind": "roleplay",
    }


SCENARIOS = [
    # ------------------------------------------------------------ Food & Drink
    S("ramen", "🍜", "Food & Drink", "Ordering Ramen", "ラーメン屋で注文",
      "Order ramen, customize toppings, and pay at a busy ramen shop.",
      "a friendly ramen shop staff member", "a hungry customer",
      "A small busy ramen shop in Tokyo at lunchtime.",
      ["ラーメン", "餃子", "大盛り", "注文", "おすすめ", "会計"]),
    S("izakaya", "🍻", "Food & Drink", "Night at an Izakaya", "居酒屋で一杯",
      "Order drinks and small dishes, chat with the staff.",
      "an izakaya staff member who loves to chat", "a customer after work",
      "A lively izakaya in the evening.",
      ["生ビール", "枝豆", "焼き鳥", "乾杯", "お通し", "とりあえず"]),
    S("cafe", "☕", "Food & Drink", "At a Café", "カフェで注文",
      "Order coffee and dessert, ask about wifi and seating.",
      "a polite café barista", "a customer who wants to relax",
      "A quiet café on a rainy afternoon.",
      ["コーヒー", "ケーキ", "席", "持ち帰り", "砂糖", "ミルク"]),
    S("sushi", "🍣", "Food & Drink", "Sushi Counter", "寿司屋のカウンター",
      "Sit at the counter, ask the chef for recommendations.",
      "a seasoned sushi chef", "a curious customer",
      "A traditional sushi restaurant counter.",
      ["握り", "まぐろ", "わさび", "お任せ", "新鮮", "醤油"]),
    S("konbini", "🏪", "Food & Drink", "Convenience Store", "コンビニで買い物",
      "Buy food, heat up a bento, pay with card.",
      "a convenience store clerk", "a customer in a hurry",
      "A convenience store at night.",
      ["温める", "お弁当", "袋", "ポイントカード", "レジ", "おにぎり"]),

    # ------------------------------------------------------------------ Travel
    S("airport", "✈️", "Travel", "At the Airport", "空港で",
      "Check in, ask about baggage and the gate.",
      "an airline check-in agent", "a traveler flying to Osaka",
      "The check-in counter at Narita Airport.",
      ["搭乗券", "荷物", "ゲート", "出発", "パスポート", "窓側"]),
    S("train", "🚄", "Travel", "Taking the Train", "電車に乗る",
      "Buy tickets, find the right platform, ask about transfers.",
      "a station attendant", "a traveler trying to reach Kyoto",
      "A large train station with many lines.",
      ["切符", "乗り換え", "ホーム", "指定席", "各駅停車", "終電"]),
    S("hotel", "🏨", "Travel", "Hotel Check-in", "ホテルのチェックイン",
      "Check in, ask about breakfast, wifi, and checkout time.",
      "a hotel receptionist", "a guest with a reservation",
      "The front desk of a business hotel.",
      ["予約", "チェックイン", "朝食", "鍵", "何時", "禁煙"]),
    S("directions", "🗺️", "Travel", "Asking for Directions", "道を聞く",
      "You're lost. Ask a local how to get to the station.",
      "a kind local person", "a lost tourist",
      "A street corner in an unfamiliar neighborhood.",
      ["まっすぐ", "右", "左", "信号", "交差点", "近く"]),
    S("taxi", "🚕", "Travel", "Taking a Taxi", "タクシーに乗る",
      "Tell the driver where to go, make small talk, pay.",
      "a chatty taxi driver", "a passenger",
      "A taxi in the city.",
      ["まで", "お願いします", "右に曲がって", "ここで", "お釣り", "領収書"]),
    S("ryokan", "♨️", "Travel", "Staying at a Ryokan", "旅館に泊まる",
      "Check in to a traditional inn, ask about the onsen and dinner.",
      "a ryokan hostess (okami)", "a guest excited about onsen",
      "A traditional ryokan in the mountains.",
      ["温泉", "浴衣", "夕食", "布団", "露天風呂", "旅館"]),

    # ---------------------------------------------------------------- Shopping
    S("clothes", "👕", "Shopping", "Buying Clothes", "服を買う",
      "Ask about sizes, colors, and try things on.",
      "a helpful clothing store clerk", "a shopper looking for a jacket",
      "A clothing store in a shopping mall.",
      ["サイズ", "試着", "色違い", "似合う", "少し", "セール"]),
    S("electronics", "📱", "Shopping", "Electronics Store", "家電量販店で",
      "Compare phones, ask about features and price.",
      "an enthusiastic electronics salesperson", "a customer choosing a new phone",
      "A big electronics store.",
      ["値段", "機能", "安い", "保証", "比べる", "電池"]),
    S("souvenir", "🎁", "Shopping", "Souvenir Shopping", "お土産を買う",
      "Pick souvenirs for family, ask for gift wrapping.",
      "a souvenir shop owner", "a tourist buying gifts",
      "A souvenir shop near a famous temple.",
      ["お土産", "包む", "有名", "人気", "別々に", "おすすめ"]),

    # -------------------------------------------------------------- Daily Life
    S("intro", "👋", "Daily Life", "First Meeting", "初めまして",
      "Introduce yourself to someone new: name, country, hobbies.",
      "a friendly Japanese person you just met", "yourself",
      "A language exchange event.",
      ["初めまして", "出身", "趣味", "仕事", "よろしく", "呼んで"]),
    S("weather", "🌦️", "Daily Life", "Weather Small Talk", "天気の話",
      "Chat about today's weather and the weekend forecast.",
      "a neighbor you bump into", "yourself",
      "Outside your apartment on a cloudy morning.",
      ["天気", "雨", "暑い", "寒い", "予報", "傘"]),
    S("weekend", "🎡", "Daily Life", "Weekend Plans", "週末の予定",
      "Talk about what you did last weekend and plans for the next.",
      "a curious friend", "yourself",
      "Chatting with a friend over lunch.",
      ["予定", "映画", "遊ぶ", "楽しみ", "疲れた", "どこか"]),
    S("hobbies", "🎸", "Daily Life", "Talking About Hobbies", "趣味について",
      "Describe your hobbies and ask about theirs.",
      "a new friend with many hobbies", "yourself",
      "A casual conversation at a café.",
      ["趣味", "好き", "始める", "上手", "毎週", "一緒に"]),
    S("family", "👨‍👩‍👧", "Daily Life", "Talking About Family", "家族について",
      "Describe your family members and ask about theirs.",
      "a warm conversation partner", "yourself",
      "A relaxed chat between friends.",
      ["家族", "兄弟", "両親", "住んでいる", "何人", "ペット"]),
    S("barber", "💇", "Daily Life", "At the Hair Salon", "美容院で",
      "Explain the haircut you want.",
      "a stylish hairdresser", "a customer",
      "A trendy hair salon.",
      ["短く", "切る", "染める", "シャンプー", "前髪", "整える"]),
    S("gym", "💪", "Daily Life", "Joining a Gym", "ジムに入会",
      "Ask about membership, hours, and facilities.",
      "a gym staff member", "someone who wants to get fit",
      "The reception of a fitness gym.",
      ["入会", "会費", "営業時間", "見学", "運動", "月々"]),

    # ------------------------------------------------------------- Work & Study
    S("interview", "💼", "Work & Study", "Job Interview", "面接",
      "A basic job interview: your background, strengths, motivation.",
      "a polite but formal interviewer", "a job applicant",
      "A meeting room at a Japanese company.",
      ["面接", "経験", "長所", "志望動機", "頑張ります", "御社"], "N4-N1"),
    S("office", "🏢", "Work & Study", "Office Small Talk", "職場の雑談",
      "Morning greetings and small talk with a coworker.",
      "a friendly senior coworker", "a new employee",
      "The office kitchen before work.",
      ["お疲れ様", "会議", "忙しい", "残業", "週末", "頑張って"]),
    S("classroom", "🎓", "Work & Study", "First Day of Class", "初めての授業",
      "Introduce yourself to your teacher and ask about the course.",
      "a kind Japanese teacher", "a new student",
      "A small language school classroom.",
      ["授業", "宿題", "質問", "教科書", "テスト", "復習"]),
    S("phone_call", "📞", "Work & Study", "Business Phone Call", "電話対応",
      "Answer a phone call, take a message.",
      "a client calling your office", "an employee answering the phone",
      "Your desk at work; the phone rings.",
      ["お電話ありがとうございます", "少々お待ちください", "伝言", "折り返し", "担当", "失礼します"], "N3-N1"),

    # ------------------------------------------------------------------ Social
    S("friends", "🤝", "Social", "Making a Friend", "友達を作る",
      "Chat with someone at a party and exchange contact info.",
      "a sociable person at a party", "yourself",
      "A house party with music and snacks.",
      ["連絡先", "LINE", "また今度", "楽しい", "紹介", "気が合う"]),
    S("karaoke", "🎤", "Social", "Karaoke Night", "カラオケで",
      "Pick songs, cheer for each other, order drinks.",
      "an enthusiastic friend who loves singing", "yourself",
      "A karaoke box with friends.",
      ["歌う", "曲", "上手", "次", "予約", "盛り上がる"]),
    S("date", "💕", "Social", "First Date", "初デート",
      "A casual first date: get to know each other over dinner.",
      "your charming date", "yourself",
      "A cozy restaurant on a Friday evening.",
      ["デート", "緊張", "素敵", "また会いたい", "楽しかった", "ごちそうする"]),
    S("festival", "🏮", "Social", "Summer Festival", "夏祭りで",
      "Explore food stalls and games with a friend at a matsuri.",
      "an excited friend showing you around", "yourself",
      "A summer festival with lanterns and yukata.",
      ["祭り", "花火", "屋台", "浴衣", "金魚すくい", "かき氷"]),

    # ------------------------------------------------------------ Emergencies
    S("doctor", "🏥", "Emergencies", "At the Doctor", "病院で",
      "Describe your symptoms and understand the doctor's advice.",
      "a calm, kind doctor", "a patient with a cold",
      "A small clinic examination room.",
      ["熱", "喉", "薬", "症状", "お大事に", "アレルギー"]),
    S("pharmacy", "💊", "Emergencies", "At the Pharmacy", "薬局で",
      "Get medicine, ask about dosage.",
      "a careful pharmacist", "a customer with a headache",
      "A neighborhood pharmacy.",
      ["頭痛", "薬", "一日三回", "食後", "副作用", "処方箋"]),
    S("lost", "👮", "Emergencies", "Lost Wallet", "財布をなくした",
      "Report your lost wallet at a police box.",
      "a helpful police officer at a koban", "someone who lost their wallet",
      "A small police box (koban) near the station.",
      ["財布", "なくした", "落とした", "届け", "中身", "見つかる"]),

    # -------------------------------------------------------------- Practical
    S("bank", "🏦", "Practical", "Opening a Bank Account", "銀行口座を開く",
      "Open an account, ask about the cash card.",
      "a meticulous bank teller", "a new resident",
      "The counter at a Japanese bank.",
      ["口座", "開く", "印鑑", "キャッシュカード", "手数料", "記入"], "N4-N1"),
    S("post", "📮", "Practical", "At the Post Office", "郵便局で",
      "Send a package abroad, choose shipping speed.",
      "a post office clerk", "a customer sending a package",
      "The counter of a post office.",
      ["小包", "送る", "航空便", "船便", "切手", "届く"]),
    S("apartment", "🏠", "Practical", "Apartment Hunting", "部屋探し",
      "Describe your ideal apartment to a real estate agent.",
      "a fast-talking real estate agent", "someone looking for an apartment",
      "A real estate agency office.",
      ["家賃", "駅から", "間取り", "敷金", "礼金", "内見"], "N4-N1"),
    S("phone_contract", "📶", "Practical", "Getting a SIM Card", "携帯の契約",
      "Sign up for a phone plan, ask about data.",
      "a mobile shop staff member", "a customer who needs a SIM",
      "A mobile phone shop.",
      ["契約", "プラン", "データ", "月額", "身分証明書", "解約"], "N4-N1"),
]


def L(id, emoji, title, title_ja, objectives, vocab, levels="N5"):
    return {
        "id": id, "emoji": emoji, "category": "Lessons", "title": title,
        "title_ja": title_ja, "description": "; ".join(objectives),
        "objectives": objectives, "target_vocab": vocab, "levels": levels,
        "kind": "lesson",
    }


LESSONS = [
    L("greetings", "🌅", "Greetings & Politeness", "あいさつ",
      ["Greet people at different times of day", "Say thank you and apologize naturally"],
      ["おはようございます", "こんばんは", "ありがとうございます", "すみません", "お願いします", "失礼します"]),
    L("self_intro", "🙋", "Self-Introduction", "自己紹介",
      ["Give a complete self-introduction", "Use です/から correctly"],
      ["と申します", "出身", "歳", "仕事", "趣味", "よろしくお願いします"]),
    L("numbers_shopping", "🔢", "Numbers & Prices", "数字と値段",
      ["Count and say prices", "Ask how much something costs"],
      ["いくら", "百", "千", "円", "高い", "安い"]),
    L("time_dates", "🕐", "Time & Dates", "時間と日付",
      ["Tell the time", "Talk about days and schedules"],
      ["何時", "半", "曜日", "今日", "明日", "毎日"]),
    L("likes_dislikes", "❤️", "Likes & Dislikes", "好きと嫌い",
      ["Express what you like and dislike", "Use が好き/が嫌い/が上手"],
      ["好き", "嫌い", "大好き", "苦手", "どんな", "一番"]),
    L("daily_routine", "🌞", "Daily Routine", "毎日の生活",
      ["Describe your daily routine with time expressions", "Use basic verbs in ます form"],
      ["起きます", "食べます", "行きます", "帰ります", "寝ます", "働きます"]),
    L("past_tense", "📅", "Talking About the Past", "過去の話",
      ["Say what you did yesterday/last weekend", "Use ました/ませんでした"],
      ["昨日", "先週", "行きました", "食べました", "楽しかった", "でした"], "N5-N4"),
    L("te_form", "🔗", "Connecting with て-form", "て形で繋ぐ",
      ["Chain actions with て-form", "Make requests with てください"],
      ["起きて", "食べて", "行って", "見て", "してください", "それから"], "N4"),
    L("feelings", "😊", "Expressing Feelings", "気持ちを伝える",
      ["Express emotions and physical states", "React naturally to news"],
      ["嬉しい", "悲しい", "疲れた", "眠い", "びっくり", "大丈夫"], "N5-N4"),
    L("keigo_basics", "🙇", "Polite Japanese Basics", "敬語の基本",
      ["Use basic keigo in service situations", "Understand common polite phrases"],
      ["いらっしゃいませ", "かしこまりました", "恐れ入ります", "いただきます", "ございます", "お待ちください"], "N3-N1"),
]

ALL = {s["id"]: s for s in SCENARIOS + LESSONS}


def catalog() -> dict:
    return {"scenarios": SCENARIOS, "lessons": LESSONS}


def get(sid: str) -> dict | None:
    return ALL.get(sid)
